version: '3.4'

services:
  # catlogapi:
  #   image: ${DOCKER_REGISTRY-}catlogapi
  #   build:
  #     context: .
  #     dockerfile: Services/Catalog/CatlogApi/Dockerfile
  catalogdb:
     image: postgres
  catlogapi:
    image: ${DOCKER_REGISTRY-}catlogapi
    build:
      context: .
      dockerfile: Services/Catalog/CatlogApi/Dockerfile

volumes:
  postgres_catalog:


