version: '3.4'

services:
  catalogdb:
     image: postgres  
     
  basketdb:
     image: postgres

  distributedcache:
     image: redis

  catlogapi:
    image: ${DOCKER_REGISTRY-}catlogapi
    build:
      context: .
      dockerfile: Services/Catalog/CatlogApi/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:

